name: Deniaz
favicon: null
layout_spectrum: 0.71035
typography_spectrum: 0.16895964997820556
title: Not all those who wander are lost.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050100'
    - '#f6deb8'
    - '#362303'
    - '#6b7600'
    - '#ba944b'
  brandStrength: 0.167959421640262
  lightness: 0.06126062758266926
  saturation: 0.24577713944017887
  rhythmicContrast: 0.03287127846851945
purpose: []
